name: Miner
main: com.rayzr522.miner.Miner
version: ${project.version}
description: A non-competitive mining game
author: Rayzr522
depend: [Vault]
loadafter: [Multiverse-Core]
commands:
  miner:
    description: Main command for Miner
    aliases: min, mn
